# Generated by Django 5.2.1 on 2025-06-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_category_crafttype_difficulty_product_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('reference_month', models.DateField(blank=True, null=True)),
                ('craft_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='catalogo.crafttype')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='catalogo.difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kits.kit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.product')),
            ],
        ),
        migrations.AddField(
            model_name='kit',
            name='products',
            field=models.ManyToManyField(through='kits.KitItem', to='catalogo.product'),
        ),
    ]
