# Generated by Django 5.2.1 on 2025-06-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_category_crafttype_difficulty_product_delete_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
