# Generated by Django 5.2.1 on 2025-06-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
